---
- name: start bitbucket
  when: bitbucket_need_installation and bitbucket_start_after_installation
  service:
    name: "{{ item }}"
    state: started
  with_items:
  - "{{ bitbucket_service_name }}_search"
  - "{{ bitbucket_service_name }}"

- name: restart bitbucket
  when: not bitbucket_need_installation
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - "{{ bitbucket_service_name }}_search"
  - "{{ bitbucket_service_name }}"
